### ISSUE TITLE
ACCESS TOKEN надо постоянно обновлять?

### ISSUE THREAD

**Issue by makc9I** [ig0r74/modInstagram#3]
Сделал все по вашей инструкции примерно месяц назад. Сегодня обнаружил, что посты на сайте отображаться перестали. Зашел в админку инсты, повторил все действия и инста выдила мне другой access token. Подставил его в настройки, и снова все заработало. Токен имеет время жизни и его придется вручную каждый раз переполучать?

**Comment by ig0r74** [comment]
Не знаю, с чем это связано, но иногда отваливается. У меня на демо-сайте ни разу не отваливался.
