### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by Gorotto** [ig0r74/modInstagram#5]
Было бы круто обновить инструкцию, т.к. с 15.10 новые условия получения и не совсем понятно как получить токен.
UPDATE: Starting October 15, 2019, new client registration and permission review on Instagram API platform are discontinued in favor of the Instagram Basic Display API.

**Comment by ig0r74** [comment]
Привет! Только увидел issue. Как раз, когда добавил возможность получения постов без токена.
